//
// will deploy w:  supabase functions deploy generate-cover-letter
//

//
// so when u got a studentId + opportunityId, this function:
//   1. reads the opportunity - employer_profiles and student_profiles -users chain with the service role key (so it works regardless of the
//      caller's RLS access), same pattern as extract-skills /
//      generate-rejection-feedback.
//   2. computes which required/nice-to-have skills the student genuinely has
//      (via the shared synonym-aware normalizeSkillName), in code - not by
//      the AI - so the letter can only reference real, verified overlap and
//      never invents a skill the student doesn't have or whatever
//   3. calls geminito write a 200-300 word professional cover letter
//      referencing only that verified overlap plus the student's real
//      translated projects/summary.
//   4. puts a small "Generated by HireMe AI" disclosure footer, likee we agrred on and put in the PRD, to meet the PRD's AI accountability requirement - so employers reading a
//      submitted application always know assistance was used
//   5. returns the letter text. Does NOT write to the database - the caller
//      PRD's AI accountability requirement - so employers reading a
//      submitted application always know assistance was used.) shows it in an editable textarea so the
//      student can review/edit before submitting, same human-in-the-loop
//      pattern as the rejection-feedback flow.
//
// @ts-nocheck

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.4";
import { normalizeSkillName, resolveNormalizedSkills } from "../_shared/skillSynonyms.ts";

const GEMINI_API_KEY = Deno.env.get("GEMINI_API_KEY");
const ANTHROPIC_API_KEY = Deno.env.get("ANTHROPIC_API_KEY");
const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

const PROVIDER = GEMINI_API_KEY ? "gemini" : "claude";

const CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const AI_DISCLOSURE_FOOTER = "Generated by HireMe AI";

function computeMatchedSkills(
  studentSkills: unknown[],
  requiredSkills: string[],
  niceToHaveSkills: string[],
  requiredSkillsNormalized: string[] | null,
  niceToHaveSkillsNormalized: string[] | null,
) {
  const known = new Set(
    (studentSkills || []).map((s: any) => normalizeSkillName(typeof s === "string" ? s : s?.skill || "")),
  );

  const required = requiredSkills || [];
  const niceToHave = niceToHaveSkills || [];
  const requiredNorm = resolveNormalizedSkills(required, requiredSkillsNormalized);
  const niceToHaveNorm = resolveNormalizedSkills(niceToHave, niceToHaveSkillsNormalized);

  const matchedRequired = required.filter((_, i) => known.has(requiredNorm[i]));
  const matchedNice = niceToHave.filter((_, i) => known.has(niceToHaveNorm[i]));

  return { matchedRequired, matchedNice };
}

async function callGemini(prompt: string) {
  const model = "gemini-2.5-flash";
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${GEMINI_API_KEY}`;

  const response = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      contents: [{ parts: [{ text: prompt }] }],
      generationConfig: { temperature: 0.6 },
    }),
  });

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(`Gemini API error (${response.status}): ${errText}`);
  }

  const data = await response.json();
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) throw new Error("No text content returned from Gemini");
  return text.trim();
}

async function callClaude(prompt: string) {
  const response = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": ANTHROPIC_API_KEY!,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model: "claude-haiku-4-5-20251001",
      max_tokens: 700,
      messages: [{ role: "user", content: prompt }],
    }),
  });

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(`Claude API error (${response.status}): ${errText}`);
  }

  const data = await response.json();
  const textBlock = data.content?.find((b: { type: string }) => b.type === "text");
  if (!textBlock?.text) throw new Error("No text content returned from Claude");
  return textBlock.text.trim();
}

async function callLLM(prompt: string) {
  if (PROVIDER === "gemini") return await callGemini(prompt);
  return await callClaude(prompt);
}

function buildPrompt({
  studentName,
  jobTitle,
  companyName,
  jobDescription,
  location,
  jobType,
  matchedRequired,
  matchedNice,
  professionalSummary,
  translatedProjects,
}: {
  studentName: string;
  jobTitle: string;
  companyName: string;
  jobDescription: string;
  location: string | null;
  jobType: string | null;
  matchedRequired: string[];
  matchedNice: string[];
  professionalSummary: string | null;
  translatedProjects: { professional_title?: string; description?: string }[];
}) {
  const projectLines = (translatedProjects || [])
    .slice(0, 3)
    .map((p) => `- ${p.professional_title || "Project"}: ${p.description || ""}`)
    .join("\n");

  return `
You are writing a first-person cover letter on behalf of a South African graduate/student
applying to a job through an AI-powered career-matching platform called HireMe. The tone
should be genuine, professional, and confident without being arrogant or generic corporate
boilerplate.

Candidate name: ${studentName}
Candidate's professional summary: ${professionalSummary || "(not available)"}
Candidate's relevant projects:
${projectLines || "(none available)"}

Job title: ${jobTitle}
Company: ${companyName}
Location: ${location || "(not specified)"}
Job type: ${jobType || "(not specified)"}
Job description: """
${jobDescription || "(no description provided)"}
"""

Skills the candidate genuinely has that match this role's requirements: ${matchedRequired.join(", ") || "none specifically identified - focus on general fit and enthusiasm instead"}
Additional nice-to-have skills the candidate also has: ${matchedNice.join(", ") || "none"}

STRICT RULES:
- ONLY reference skills, projects, and experience listed above. Never invent a skill, employer, qualification, or achievement not given to you.
- Do not claim the candidate has any skill not in the two lists above, even if the job description mentions it.
- Write 200-300 words.
- Format: a greeting ("Dear Hiring Team," or "Dear [Company Name] Hiring Team,"), exactly 3 body paragraphs, then a closing ("Sincerely," followed by the candidate's name on the next line).
  - Paragraph 1: express genuine interest in this specific role and company.
  - Paragraph 2: connect the candidate's real matched skills/projects to the role's needs.
  - Paragraph 3: reiterate enthusiasm and invite next steps (interview).
- Plain text only - no markdown, no bullet points, no headings.
- Output ONLY the letter text itself, nothing before or after it.
`;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: CORS_HEADERS });
  }

  try {
    if (!GEMINI_API_KEY && !ANTHROPIC_API_KEY) {
      throw new Error("No LLM provider configured. Set GEMINI_API_KEY (free) or ANTHROPIC_API_KEY (paid) as a secret.");
    }

    const { studentId, opportunityId } = await req.json();
    if (!studentId || !opportunityId) {
      return new Response(
        JSON.stringify({ success: false, error: "studentId and opportunityId are required" }),
        { status: 400, headers: { ...CORS_HEADERS, "Content-Type": "application/json" } },
      );
    }

    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

    const { data: opportunity, error: oppError } = await supabase
      .from("opportunities")
      .select(
        "title, description, required_skills, nice_to_have_skills, required_skills_normalized, nice_to_have_skills_normalized, location, job_type, employer_id",
      )
      .eq("id", opportunityId)
      .single();
    if (oppError) throw oppError;

    const { data: employerProfile } = await supabase
      .from("employer_profiles")
      .select("company_name")
      .eq("id", opportunity.employer_id)
      .single();

    const { data: studentProfile, error: profileError } = await supabase
      .from("student_profiles")
      .select("extracted_technical_skills, professional_summary, translated_projects")
      .eq("id", studentId)
      .single();
    if (profileError) throw profileError;

    const { data: studentUser } = await supabase
      .from("users")
      .select("full_name")
      .eq("id", studentId)
      .single();

    const { matchedRequired, matchedNice } = computeMatchedSkills(
      studentProfile.extracted_technical_skills || [],
      opportunity.required_skills || [],
      opportunity.nice_to_have_skills || [],
      opportunity.required_skills_normalized,
      opportunity.nice_to_have_skills_normalized,
    );

    const prompt = buildPrompt({
      studentName: studentUser?.full_name || "the candidate",
      jobTitle: opportunity.title,
      companyName: employerProfile?.company_name || "the company",
      jobDescription: opportunity.description,
      location: opportunity.location,
      jobType: opportunity.job_type,
      matchedRequired,
      matchedNice,
      professionalSummary: studentProfile.professional_summary,
      translatedProjects: studentProfile.translated_projects || [],
    });

    const letter = await callLLM(prompt);
    const coverLetter = `${letter}\n\n— ${AI_DISCLOSURE_FOOTER}`;

    return new Response(JSON.stringify({ success: true, provider: PROVIDER, coverLetter }), {
      headers: { ...CORS_HEADERS, "Content-Type": "application/json" },
    });
  } catch (error) {
    console.error("generate-cover-letter error:", error);
    return new Response(
      JSON.stringify({ success: false, error: error instanceof Error ? error.message : "Unknown error" }),
      { status: 500, headers: { ...CORS_HEADERS, "Content-Type": "application/json" } },
    );
  }
});
